"use client";

import { LegalLayout } from "@/components/layout/legal-layout";
import { useLocale } from "@/lib/i18n/locale-context";

function PrivacyContent() {
  const { locale } = useLocale();

  if (locale === "en") {
    return (
      <article className="prose prose-neutral max-w-none font-body">
        <h1 className="font-display text-3xl font-bold text-text-primary">
          Privacy Policy
        </h1>
        <p className="text-text-secondary">Last updated: May 2026</p>

        <p>
          This Privacy Policy explains what data Flipia collects, how we use it, who we share it with, and the rights you have over your data. It applies to the Flipia mobile app on Android and iOS and to this website.
        </p>

        <h2>1. Information We Collect</h2>
        <ul>
          <li><strong>Google account data</strong> (only if you sign in with Google): Google ID, name, and email address provided by Google Sign-In.</li>
          <li><strong>Guest account data</strong> (if you play as a Guest): a pseudonymous user identifier generated by InstantDB, with no real-world identity attached.</li>
          <li><strong>Game profile:</strong> nickname, avatar (emoji), selected board.</li>
          <li><strong>Progression data:</strong> XP, level, points, wins, losses, current and best streaks, unlocked achievements.</li>
          <li><strong>Game history:</strong> difficulty, scores, duration, opponent type (human/bot), and full game state of multiplayer rooms.</li>
          <li><strong>Multiplayer data:</strong> room codes, real-time game state, timestamps of moves.</li>
          <li><strong>Technical data:</strong> platform (Android/iOS), OS version, app version, device type.</li>
          <li><strong>Feedback data</strong> (only if you submit feedback): category, message, optional email address.</li>
          <li><strong>Purchase data:</strong> in-app purchase history and active entitlements (linked via your InstantDB user ID through RevenueCat).</li>
          <li><strong>Advertising identifiers:</strong> GAID on Android, IDFA on iOS, collected by Google AdMob subject to your device-level consent.</li>
        </ul>

        <h2>2. How We Use Your Data</h2>
        <ul>
          <li>Authenticate you and maintain your session</li>
          <li>Display your profile, statistics, achievements, and leaderboard position</li>
          <li>Enable real-time multiplayer (room creation, matchmaking, game state synchronization)</li>
          <li>Process and validate in-app purchases and entitlements (Premium, packs)</li>
          <li>Show advertisements and, with your consent, personalize them</li>
          <li>Provide customer support and respond to your feedback</li>
          <li>Improve the app, fix bugs, and prevent cheating</li>
        </ul>

        <h2>3. Legal Basis (GDPR)</h2>
        <ul>
          <li><strong>Performance of a contract:</strong> creating and maintaining your account, providing the game features you request.</li>
          <li><strong>Consent:</strong> personalized advertising, push/local notifications, optional feedback.</li>
          <li><strong>Legitimate interest:</strong> security, anti-cheat, fraud prevention, service improvement.</li>
          <li><strong>Legal obligation:</strong> bookkeeping for purchases as required by applicable law.</li>
        </ul>

        <h2>4. Data Storage and Sub-Processors</h2>
        <p>We rely on the following service providers to operate Flipia:</p>
        <ul>
          <li><strong>InstantDB</strong> (United States) — real-time database for profiles, leaderboard, game history, and multiplayer rooms; also handles authentication via Google ID token.</li>
          <li><strong>Google Sign-In / Google OAuth</strong> — provides your Google identity (email, name) when you choose this sign-in method.</li>
          <li><strong>Google AdMob</strong> — serves interstitial and rewarded advertisements; collects advertising identifiers.</li>
          <li><strong>RevenueCat</strong> — manages in-app purchases and links them to your user ID; receives purchase events from the stores.</li>
          <li><strong>Supabase</strong> (United States) — stores only the feedback you submit through the in-app form; no authentication session is persisted.</li>
          <li><strong>Google Play Store / Apple App Store</strong> — distribute the app, process payments for in-app purchases, deliver in-app updates.</li>
          <li><strong>AsyncStorage</strong> — local on-device storage for preferences (theme, onboarding state, daily reward timestamps, notification flags). No transmission to a server.</li>
        </ul>

        <h2>5. Advertising and Advertising Identifiers</h2>
        <p>
          Flipia uses <strong>Google AdMob</strong> to display interstitial ads (about once every three games) and optional rewarded ads (in exchange for XP). AdMob may collect your device&apos;s <strong>advertising identifier</strong> (GAID on Android, IDFA on iOS), interaction events, and approximate inferred information to deliver and measure ads.
        </p>
        <p>
          You can <strong>limit ad tracking or reset your advertising ID</strong> at any time in your device settings (Android: Settings &gt; Privacy &gt; Ads; iOS: Settings &gt; Privacy &amp; Security &gt; Tracking). Purchasing <strong>Flipia Premium</strong> removes all ads.
        </p>

        <h2>6. Notifications</h2>
        <p>
          With your permission, Flipia schedules a <strong>local daily notification at 6 PM</strong> to remind you of your daily XP reward. Notifications are generated locally on your device — no push token is sent to a remote server. You can disable notifications at any time in your device settings.
        </p>

        <h2>7. Public Visibility and Data Sharing</h2>
        <p>
          We do <strong>not sell, rent, or share your personal data with third parties for marketing purposes</strong>. The following information is, however, visible to other Flipia users:
        </p>
        <ul>
          <li>Your <strong>nickname</strong>, <strong>avatar</strong>, and progression stats (XP, level, wins, games played) on the global leaderboard and your public player profile.</li>
          <li>Your nickname and avatar to your opponent in multiplayer matches.</li>
        </ul>
        <p>
          Your Google email is <strong>never displayed publicly</strong>. Data is shared with our sub-processors only as needed to operate the service (see Section 4).
        </p>

        <h2>8. Data Retention</h2>
        <ul>
          <li>Account and game data are kept as long as your account is active.</li>
          <li>Feedback messages are kept as long as needed to provide support and improve the app.</li>
          <li>Purchase records are kept for the duration required by applicable accounting and consumer-protection law.</li>
          <li>Upon deletion request, your personal data is removed from our active databases within a reasonable delay; aggregated and anonymized statistics may be retained.</li>
        </ul>

        <h2>9. Your Rights</h2>
        <p>Depending on your jurisdiction (GDPR, UK GDPR, CCPA, etc.), you have the right to:</p>
        <ul>
          <li><strong>Access</strong> the personal data we hold about you</li>
          <li><strong>Rectify</strong> inaccurate data (you can update your nickname and avatar in-app at any time)</li>
          <li><strong>Erase</strong> your account and associated cloud data</li>
          <li><strong>Object</strong> to processing or <strong>withdraw consent</strong> (e.g., personalized ads, notifications)</li>
          <li><strong>Portability</strong> — receive a copy of your data in a structured format</li>
          <li><strong>Lodge a complaint</strong> with your local data-protection authority</li>
        </ul>
        <p>
          To exercise any of these rights — including <strong>account deletion</strong>, which is not yet available as an in-app button — please email us at <strong>simplice2236@gmail.com</strong>. We will respond within 30 days.
        </p>

        <h2>10. International Data Transfers</h2>
        <p>
          InstantDB, Supabase, Google, Apple, and RevenueCat are based in the United States or operate global infrastructure. By using Flipia, you acknowledge that your data may be transferred to and stored in countries outside your country of residence. Where required, these transfers are protected by the European Commission&apos;s <strong>Standard Contractual Clauses</strong> or equivalent safeguards.
        </p>

        <h2>11. Children&apos;s Privacy</h2>
        <p>
          Flipia is not directed at children under <strong>13</strong>. We do not knowingly collect personal data from children under 13. In the EEA and UK, children under 16 must obtain parental consent before using the app. Our advertising integration with AdMob is configured for an audience aged 13+. If you believe a child under 13 has provided data, please contact us so we can delete it. We comply with the U.S. <strong>COPPA</strong> requirements and the GDPR rules on minors.
        </p>

        <h2>12. Security</h2>
        <p>
          All communications between the app and our service providers use <strong>HTTPS encryption</strong>. Authentication is delegated to Google OAuth — we never store your Google password. Despite reasonable safeguards, no online service is 100% secure; we cannot guarantee absolute security.
        </p>

        <h2>13. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. The &quot;Last updated&quot; date at the top of this page will reflect any change. Material changes will be communicated via the app or by updating this page.
        </p>

        <h2>14. Contact</h2>
        <p>
          For any privacy question, request to exercise your rights, or account deletion: <strong>simplice2236@gmail.com</strong>
        </p>
      </article>
    );
  }

  return (
    <article className="prose prose-neutral max-w-none font-body">
      <h1 className="font-display text-3xl font-bold text-text-primary">
        Politique de confidentialité
      </h1>
      <p className="text-text-secondary">Dernière mise à jour : Mai 2026</p>

      <p>
        Cette Politique de confidentialité explique quelles données Flipia collecte, comment nous les utilisons, avec qui nous les partageons et les droits dont vous disposez sur vos données. Elle s&apos;applique à l&apos;application mobile Flipia sur Android et iOS ainsi qu&apos;à ce site web.
      </p>

      <h2>1. Données collectées</h2>
      <ul>
        <li><strong>Données de compte Google</strong> (uniquement si vous vous connectez avec Google)&nbsp;: identifiant Google, nom et adresse email fournis par Google Sign-In.</li>
        <li><strong>Données de compte Invité</strong> (si vous jouez en mode Invité)&nbsp;: un identifiant utilisateur pseudonyme généré par InstantDB, sans lien avec votre identité réelle.</li>
        <li><strong>Profil de jeu&nbsp;:</strong> pseudo, avatar (emoji), plateau sélectionné.</li>
        <li><strong>Données de progression&nbsp;:</strong> XP, niveau, points, victoires, défaites, séries actuelle et meilleure, achievements débloqués.</li>
        <li><strong>Historique de parties&nbsp;:</strong> difficulté, scores, durée, type d&apos;adversaire (humain/bot) et état complet des salles multijoueur.</li>
        <li><strong>Données multijoueur&nbsp;:</strong> codes de salle, état du jeu en temps réel, horodatage des coups.</li>
        <li><strong>Données techniques&nbsp;:</strong> plateforme (Android/iOS), version de l&apos;OS, version de l&apos;application, type d&apos;appareil.</li>
        <li><strong>Données de feedback</strong> (uniquement si vous envoyez un retour)&nbsp;: catégorie, message, adresse email optionnelle.</li>
        <li><strong>Données d&apos;achat&nbsp;:</strong> historique des achats intégrés et droits actifs (liés à votre identifiant InstantDB via RevenueCat).</li>
        <li><strong>Identifiants publicitaires&nbsp;:</strong> GAID sur Android, IDFA sur iOS, collectés par Google AdMob sous réserve du consentement géré au niveau de l&apos;appareil.</li>
      </ul>

      <h2>2. Utilisation des données</h2>
      <ul>
        <li>Vous authentifier et maintenir votre session</li>
        <li>Afficher votre profil, statistiques, achievements et position au classement</li>
        <li>Activer le multijoueur temps réel (création de salle, matchmaking, synchronisation)</li>
        <li>Traiter et valider les achats intégrés et droits associés (Premium, packs)</li>
        <li>Diffuser des publicités et, avec votre consentement, les personnaliser</li>
        <li>Fournir le support utilisateur et répondre à vos feedbacks</li>
        <li>Améliorer l&apos;application, corriger les bugs et prévenir la triche</li>
      </ul>

      <h2>3. Base légale (RGPD)</h2>
      <ul>
        <li><strong>Exécution du contrat&nbsp;:</strong> création et maintien de votre compte, mise à disposition des fonctionnalités du jeu.</li>
        <li><strong>Consentement&nbsp;:</strong> publicités personnalisées, notifications locales, feedback optionnel.</li>
        <li><strong>Intérêt légitime&nbsp;:</strong> sécurité, anti-triche, prévention de la fraude, amélioration du service.</li>
        <li><strong>Obligation légale&nbsp;:</strong> conservation des données d&apos;achat selon la loi comptable et de protection du consommateur.</li>
      </ul>

      <h2>4. Stockage et sous-traitants</h2>
      <p>Nous utilisons les prestataires suivants pour exploiter Flipia&nbsp;:</p>
      <ul>
        <li><strong>InstantDB</strong> (États-Unis) — base de données temps réel pour les profils, le classement, l&apos;historique de parties et les salles multijoueur&nbsp;; gère aussi l&apos;authentification via le token d&apos;identité Google.</li>
        <li><strong>Google Sign-In / Google OAuth</strong> — fournit votre identité Google (email, nom) lorsque vous choisissez ce mode de connexion.</li>
        <li><strong>Google AdMob</strong> — diffuse les publicités interstitielles et récompensées&nbsp;; collecte des identifiants publicitaires.</li>
        <li><strong>RevenueCat</strong> — gère les achats intégrés et les lie à votre identifiant utilisateur&nbsp;; reçoit les événements d&apos;achat des stores.</li>
        <li><strong>Supabase</strong> (États-Unis) — stocke uniquement les feedbacks soumis via le formulaire in-app&nbsp;; aucune session d&apos;authentification n&apos;est persistée.</li>
        <li><strong>Google Play Store / Apple App Store</strong> — distribuent l&apos;application, traitent les paiements pour les achats intégrés et livrent les mises à jour.</li>
        <li><strong>AsyncStorage</strong> — stockage local sur votre appareil pour les préférences (thème, onboarding, dates de récompenses, statuts des notifications). Aucune transmission à un serveur.</li>
      </ul>

      <h2>5. Publicité et identifiants publicitaires</h2>
      <p>
        Flipia utilise <strong>Google AdMob</strong> pour afficher des publicités interstitielles (environ une toutes les trois parties) et des publicités récompensées optionnelles (en échange d&apos;XP). AdMob peut collecter <strong>l&apos;identifiant publicitaire</strong> de votre appareil (GAID sur Android, IDFA sur iOS), des événements d&apos;interaction et des informations déduites approximatives pour diffuser et mesurer les publicités.
      </p>
      <p>
        Vous pouvez <strong>limiter le suivi publicitaire ou réinitialiser votre identifiant</strong> à tout moment dans les paramètres de votre appareil (Android&nbsp;: Paramètres &gt; Confidentialité &gt; Publicités&nbsp;; iOS&nbsp;: Réglages &gt; Confidentialité et sécurité &gt; Suivi). L&apos;achat de <strong>Flipia Premium</strong> supprime toutes les publicités.
      </p>

      <h2>6. Notifications</h2>
      <p>
        Avec votre permission, Flipia planifie une <strong>notification locale quotidienne à 18&nbsp;h</strong> pour vous rappeler votre récompense XP du jour. Les notifications sont générées localement sur votre appareil — aucun token push n&apos;est envoyé à un serveur distant. Vous pouvez désactiver les notifications à tout moment dans les paramètres de votre appareil.
      </p>

      <h2>7. Visibilité publique et partage des données</h2>
      <p>
        Nous ne <strong>vendons, louons ni partageons vos données personnelles à des fins marketing</strong>. Les informations suivantes sont toutefois visibles par les autres utilisateurs de Flipia&nbsp;:
      </p>
      <ul>
        <li>Votre <strong>pseudo</strong>, votre <strong>avatar</strong> et vos statistiques de progression (XP, niveau, victoires, parties jouées) sur le classement global et votre profil joueur public.</li>
        <li>Votre pseudo et avatar sont visibles par votre adversaire lors des parties multijoueur.</li>
      </ul>
      <p>
        Votre email Google n&apos;est <strong>jamais affiché publiquement</strong>. Les données ne sont partagées avec nos sous-traitants qu&apos;aux fins de l&apos;exploitation du service (voir Section&nbsp;4).
      </p>

      <h2>8. Durée de conservation</h2>
      <ul>
        <li>Les données de compte et de jeu sont conservées tant que votre compte est actif.</li>
        <li>Les messages de feedback sont conservés le temps nécessaire au support et à l&apos;amélioration de l&apos;application.</li>
        <li>Les enregistrements d&apos;achat sont conservés pour la durée requise par la loi comptable et la protection du consommateur.</li>
        <li>Sur demande de suppression, vos données personnelles sont retirées de nos bases actives dans un délai raisonnable&nbsp;; des statistiques agrégées et anonymisées peuvent être conservées.</li>
      </ul>

      <h2>9. Vos droits</h2>
      <p>Selon votre juridiction (RGPD, UK GDPR, CCPA, etc.), vous disposez du droit&nbsp;:</p>
      <ul>
        <li><strong>D&apos;accès</strong> aux données personnelles que nous détenons</li>
        <li><strong>De rectification</strong> des données inexactes (vous pouvez modifier votre pseudo et votre avatar dans l&apos;app à tout moment)</li>
        <li><strong>D&apos;effacement</strong> de votre compte et des données cloud associées</li>
        <li><strong>D&apos;opposition</strong> au traitement ou de <strong>retrait du consentement</strong> (ex.&nbsp;: pubs personnalisées, notifications)</li>
        <li><strong>De portabilité</strong> — recevoir une copie de vos données dans un format structuré</li>
        <li><strong>D&apos;introduire une réclamation</strong> auprès de votre autorité locale de protection des données</li>
      </ul>
      <p>
        Pour exercer l&apos;un de ces droits — y compris la <strong>suppression de compte</strong>, qui n&apos;est pas encore disponible via un bouton in-app — veuillez nous écrire à <strong>simplice2236@gmail.com</strong>. Nous répondrons sous 30&nbsp;jours.
      </p>

      <h2>10. Transferts internationaux</h2>
      <p>
        InstantDB, Supabase, Google, Apple et RevenueCat sont basés aux États-Unis ou exploitent une infrastructure mondiale. En utilisant Flipia, vous reconnaissez que vos données peuvent être transférées et stockées dans des pays hors de votre pays de résidence. Lorsque requis, ces transferts sont encadrés par les <strong>Clauses Contractuelles Types</strong> de la Commission européenne ou des garanties équivalentes.
      </p>

      <h2>11. Mineurs</h2>
      <p>
        Flipia ne s&apos;adresse pas aux enfants de moins de <strong>13&nbsp;ans</strong>. Nous ne collectons pas sciemment de données personnelles d&apos;enfants de moins de 13&nbsp;ans. Dans l&apos;EEE et au Royaume-Uni, les enfants de moins de 16&nbsp;ans doivent obtenir le consentement parental avant d&apos;utiliser l&apos;application. Notre intégration publicitaire AdMob est configurée pour un public de 13&nbsp;ans et plus. Si vous pensez qu&apos;un enfant de moins de 13&nbsp;ans nous a fourni des données, contactez-nous afin que nous puissions les supprimer. Nous respectons les exigences <strong>COPPA</strong> aux États-Unis et les règles du RGPD relatives aux mineurs.
      </p>

      <h2>12. Sécurité</h2>
      <p>
        Toutes les communications entre l&apos;application et nos prestataires utilisent le <strong>chiffrement HTTPS</strong>. L&apos;authentification est déléguée à Google OAuth — nous ne stockons jamais votre mot de passe Google. Malgré des mesures de sécurité raisonnables, aucun service en ligne n&apos;est 100&nbsp;% sécurisé&nbsp;; nous ne pouvons garantir une sécurité absolue.
      </p>

      <h2>13. Modifications de cette politique</h2>
      <p>
        Nous pouvons mettre à jour cette Politique de confidentialité périodiquement. La date «&nbsp;Dernière mise à jour&nbsp;» en haut de cette page reflètera toute modification. Les changements importants seront communiqués via l&apos;application ou par mise à jour de cette page.
      </p>

      <h2>14. Contact</h2>
      <p>
        Pour toute question de confidentialité, demande d&apos;exercice de vos droits ou suppression de compte&nbsp;: <strong>simplice2236@gmail.com</strong>
      </p>
    </article>
  );
}

export default function PrivacyPage() {
  return (
    <LegalLayout>
      <PrivacyContent />
    </LegalLayout>
  );
}
