export function PrivacyEN() {
  return (

      <article className="prose prose-neutral max-w-none font-body">
        <h1 className="font-display text-3xl font-bold text-text-primary">
          Privacy Policy
        </h1>
        <p className="text-text-secondary">Last updated: May 2026</p>

        <p>
          This Privacy Policy explains what data Flipia collects, how we use it, who we share it with, and the rights you have over your data. It applies to the Flipia mobile app on Android and iOS and to this website.
        </p>

        <h2>1. Information We Collect</h2>
        <ul>
          <li><strong>Google account data</strong> (only if you sign in with Google): Google ID, name, and email address provided by Google Sign-In.</li>
          <li><strong>Guest account data</strong> (if you play as a Guest): a pseudonymous user identifier generated by InstantDB, with no real-world identity attached.</li>
          <li><strong>Game profile:</strong> nickname, avatar (emoji), selected board.</li>
          <li><strong>Progression data:</strong> XP, level, points, wins, losses, current and best streaks, unlocked achievements.</li>
          <li><strong>Game history:</strong> difficulty, scores, duration, opponent type (human/bot), and full game state of multiplayer rooms.</li>
          <li><strong>Multiplayer data:</strong> room codes, real-time game state, timestamps of moves.</li>
          <li><strong>Technical data:</strong> platform (Android/iOS), OS version, app version, device type.</li>
          <li><strong>Feedback data</strong> (only if you submit feedback): category, message, optional email address.</li>
          <li><strong>Purchase data:</strong> in-app purchase history and active entitlements (linked via your InstantDB user ID through RevenueCat).</li>
          <li><strong>Advertising identifiers:</strong> GAID on Android, IDFA on iOS, collected by Google AdMob subject to your device-level consent.</li>
        </ul>

        <h2>2. How We Use Your Data</h2>
        <ul>
          <li>Authenticate you and maintain your session</li>
          <li>Display your profile, statistics, achievements, and leaderboard position</li>
          <li>Enable real-time multiplayer (room creation, matchmaking, game state synchronization)</li>
          <li>Process and validate in-app purchases and entitlements (Premium, packs)</li>
          <li>Show advertisements and, with your consent, personalize them</li>
          <li>Provide customer support and respond to your feedback</li>
          <li>Improve the app, fix bugs, and prevent cheating</li>
        </ul>

        <h2>3. Legal Basis (GDPR)</h2>
        <ul>
          <li><strong>Performance of a contract:</strong> creating and maintaining your account, providing the game features you request.</li>
          <li><strong>Consent:</strong> personalized advertising, push/local notifications, optional feedback.</li>
          <li><strong>Legitimate interest:</strong> security, anti-cheat, fraud prevention, service improvement.</li>
          <li><strong>Legal obligation:</strong> bookkeeping for purchases as required by applicable law.</li>
        </ul>

        <h2>4. Data Storage and Sub-Processors</h2>
        <p>We rely on the following service providers to operate Flipia:</p>
        <ul>
          <li><strong>InstantDB</strong> (United States) — real-time database for profiles, leaderboard, game history, and multiplayer rooms; also handles authentication via Google ID token.</li>
          <li><strong>Google Sign-In / Google OAuth</strong> — provides your Google identity (email, name) when you choose this sign-in method.</li>
          <li><strong>Google AdMob</strong> — serves interstitial and rewarded advertisements; collects advertising identifiers.</li>
          <li><strong>RevenueCat</strong> — manages in-app purchases and links them to your user ID; receives purchase events from the stores.</li>
          <li><strong>Supabase</strong> (United States) — stores only the feedback you submit through the in-app form; no authentication session is persisted.</li>
          <li><strong>Google Play Store / Apple App Store</strong> — distribute the app, process payments for in-app purchases, deliver in-app updates.</li>
          <li><strong>AsyncStorage</strong> — local on-device storage for preferences (theme, onboarding state, daily reward timestamps, notification flags). No transmission to a server.</li>
        </ul>

        <h2>5. Advertising and Advertising Identifiers</h2>
        <p>
          Flipia uses <strong>Google AdMob</strong> to display interstitial ads (about once every three games) and optional rewarded ads (in exchange for XP). AdMob may collect your device&apos;s <strong>advertising identifier</strong> (GAID on Android, IDFA on iOS), interaction events, and approximate inferred information to deliver and measure ads.
        </p>
        <p>
          You can <strong>limit ad tracking or reset your advertising ID</strong> at any time in your device settings (Android: Settings &gt; Privacy &gt; Ads; iOS: Settings &gt; Privacy &amp; Security &gt; Tracking). Purchasing <strong>Flipia Premium</strong> removes all ads.
        </p>

        <h2>6. Notifications</h2>
        <p>
          With your permission, Flipia schedules a <strong>local daily notification at 6 PM</strong> to remind you of your daily XP reward. Notifications are generated locally on your device — no push token is sent to a remote server. You can disable notifications at any time in your device settings.
        </p>

        <h2>7. Public Visibility and Data Sharing</h2>
        <p>
          We do <strong>not sell, rent, or share your personal data with third parties for marketing purposes</strong>. The following information is, however, visible to other Flipia users:
        </p>
        <ul>
          <li>Your <strong>nickname</strong>, <strong>avatar</strong>, and progression stats (XP, level, wins, games played) on the global leaderboard and your public player profile.</li>
          <li>Your nickname and avatar to your opponent in multiplayer matches.</li>
        </ul>
        <p>
          Your Google email is <strong>never displayed publicly</strong>. Data is shared with our sub-processors only as needed to operate the service (see Section 4).
        </p>

        <h2>8. Data Retention</h2>
        <ul>
          <li>Account and game data are kept as long as your account is active.</li>
          <li>Feedback messages are kept as long as needed to provide support and improve the app.</li>
          <li>Purchase records are kept for the duration required by applicable accounting and consumer-protection law.</li>
          <li>Upon deletion request, your personal data is removed from our active databases within a reasonable delay; aggregated and anonymized statistics may be retained.</li>
        </ul>

        <h2>9. Your Rights</h2>
        <p>Depending on your jurisdiction (GDPR, UK GDPR, CCPA, etc.), you have the right to:</p>
        <ul>
          <li><strong>Access</strong> the personal data we hold about you</li>
          <li><strong>Rectify</strong> inaccurate data (you can update your nickname and avatar in-app at any time)</li>
          <li><strong>Erase</strong> your account and associated cloud data</li>
          <li><strong>Object</strong> to processing or <strong>withdraw consent</strong> (e.g., personalized ads, notifications)</li>
          <li><strong>Portability</strong> — receive a copy of your data in a structured format</li>
          <li><strong>Lodge a complaint</strong> with your local data-protection authority</li>
        </ul>
        <p>
          To exercise any of these rights — including <strong>account deletion</strong>, which is not yet available as an in-app button — please email us at <a href="mailto:contact@dzeryhago.com"><strong>contact@dzeryhago.com</strong></a>. We will respond within 30 days.
        </p>

        <h2>10. International Data Transfers</h2>
        <p>
          InstantDB, Supabase, Google, Apple, and RevenueCat are based in the United States or operate global infrastructure. By using Flipia, you acknowledge that your data may be transferred to and stored in countries outside your country of residence. Where required, these transfers are protected by the European Commission&apos;s <strong>Standard Contractual Clauses</strong> or equivalent safeguards.
        </p>

        <h2>11. Children&apos;s Privacy</h2>
        <p>
          Flipia is not directed at children under <strong>13</strong>. We do not knowingly collect personal data from children under 13. In the EEA and UK, children under 16 must obtain parental consent before using the app. Our advertising integration with AdMob is configured for an audience aged 13+. If you believe a child under 13 has provided data, please contact us so we can delete it. We comply with the U.S. <strong>COPPA</strong> requirements and the GDPR rules on minors.
        </p>

        <h2>12. Security</h2>
        <p>
          All communications between the app and our service providers use <strong>HTTPS encryption</strong>. Authentication is delegated to Google OAuth — we never store your Google password. Despite reasonable safeguards, no online service is 100% secure; we cannot guarantee absolute security.
        </p>

        <h2>13. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. The &quot;Last updated&quot; date at the top of this page will reflect any change. Material changes will be communicated via the app or by updating this page.
        </p>

        <h2>14. Contact</h2>
        <p>
          For any privacy question, request to exercise your rights, or account deletion: <a href="mailto:contact@dzeryhago.com"><strong>contact@dzeryhago.com</strong></a>
        </p>
      </article>
  );
}
